#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
Usage:
    xdict [<word>]
'''


import docopt
import sys
import os
from requests_html import HTMLSession


def translate(word):
    session = HTMLSession()
    r = session.get(os.path.join('http://dict.cn/', word))
    sel = '#content > div.main > div.word > div.basic.clearfix > ul > li'

    translate_items = r.html.find(sel)[:-1]
    for item in translate_items:
        attr = item.find('span', first=True)
        translation = item.find('strong', first=True)
        if attr:
            print(attr.text, end='')
        if translation:
            print(translation.text)


def repl():
    while True:
        try:
            word = input('>>> ')
            translate(word)
            print('')
        except KeyboardInterrupt:
            return


if __name__ == '__main__':
    args = docopt.docopt(__doc__)

    if args['<word>'] is not None:
        translate(args['<word>'])
    else:
        repl()
